### PR TITLE
replaced old escaping mechanism with CDATA tags

### PR DESCRIPTION
**Pull request by Achiel**
Didn't hear from you guys on the mailing list (but I assume you're sleeping at the moment). I went ahead and proposed a patch. Let me know what you guys think. 

An alternative might be to create some kind of setting for this. If that's what you prefer I wouldn't mind working on that. 

regards,
Achiel

### CODE REVIEW

**Comment by legastero** [comment]
Oh boy, I just finished reading the mailing list discussion.

Is this request due to just stylistic preference? I.e, using JSON results in huge numbers of escape entities and CDATA would be cleaner/smaller. Or have you seen any bugs resulting from using entities that using CDATA would prevent?

I see that once you have about four or so " characters, CDATA produces a shorter escaped string (so long as there are no ]]> sequences).

In the end, the facts of the matter are that when TLS is used the compression essentially negates any difference in the escaping length, and it takes roughly the same amount of CPU to perform the escaping either way (it is O(n) for both, and they take about the same number of passes if done properly).

Sleek reads/writes just fine with both methods from what I've tested, so for now I would go with having some stream level flag for choosing the desired mechanism. Maybe `self.escape_mode = 'CDATA'` or `self.use_cdata = True`

**Comment by Achiel** [comment]
commented inline:

On Tue, Nov 15, 2011 at 6:49 PM, Lance Stout
reply@reply.github.com
wrote:

> Oh boy, I just finished reading the mailing list discussion.

Yeah, sorry about that :)

> Is this request due to just stylistic preference? I.e, using JSON results in huge numbers of escape entities and CDATA would be cleaner/smaller. Or have you seen any bugs resulting from using entities that using CDATA would prevent?

I'm currently working in an environment where I talk with smack (java)
and a bot, which won't accept the current escaping mechanism out of
the box. So it's not really due to a stylistic preference, although I
do personally prefer CDATA ;)

> I see that once you have about four or so " characters, CDATA produces a shorter escaped string (so long as there are no ]]> sequences).

Yup, and like I mentioned in the mailing, any message that doesn't
contain any of these characters doesn't need the CDATA, so the effect
should be nihil in 99% (or whatever) of the cases.

> In the end, the facts of the matter are that when TLS is used the compression essentially negates any difference in the escaping length, and it takes roughly the same amount of CPU to perform the escaping either way (it is O(n) for both, and they take about the same number of passes if done properly).
> 
> Sleek reads/writes just fine with both methods from what I've tested, so for now I would go with having some stream level flag for choosing the desired mechanism. Maybe `self.escape_mode = 'CDATA'` or `self.use_cdata = True`

Sounds good to me. Haven't touched those parts of the code before but
if you'd like I can go ahead and try to create a patch.

**Comment by legastero** [comment]
Finally added, with self.use_cdata to control its use (defaults to False)

**Comment by Achiel** [comment]
Great, thanks a lot!

**Pull request closed without merging**
