### PR TITLE
Comments in the examples mention pydns...

### PR DESCRIPTION
**Pull request by rhcarvalho**
... but SleekXMPP uses _dnspython_, not _pydns_.

This is an inoffensive change that affects only comments, but that can save someone's sanity when reading the comments and seeking for help.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
I also found an apparently incorrect docstring in Message.normal.

**Comment by legastero** [comment]
Excellent! Switch the merge branch to develop and I'll pull this in now.

**Comment by rhcarvalho** [comment]
I hope I did it right :)

**Comment by legastero** [comment]
Yep, thanks!

**Pull request closed without merging**
