### PR TITLE
SleekXMPP working with gevent in a transparent way

### PR DESCRIPTION
**Pull request by pvicente**
Some changes to work with gevent if this library make the monkey patch to system libraries like (sockets, threads ...).

Modified Queue imports to work with gevent.Queue if it is loaded.

Added parameter to testall.py to load gevent and make monkey.patch_all(). Now you can test all suite with gevent loaded typing ./testall.py gevent. All tests are working fine.

It seems that library is 3x faster with gevent (testall.py gevent 6s vs testall.py 20s in my machine).

I think that these commits don't modify any feature of the library and make it to work with gevent in a transparent way. Also any other projects that are working with SleekXMPP and gevent could work without problems.

### CODE REVIEW

**Comment by legastero** [comment]
We've been discussing if we should make gevent a requirement, but if we can keep it an optional optimization this is awesome.

This will need to be applied toward the develop branch, not master, first though.

**Comment by pvicente** [comment]
As I have been investigating gevent can be an optional optimization in any python project due to it make standard library to work asyncronous (with threads, sockets, dns, etc, etc, thanks to libevent base of this library up to 0.13.6. Currently on gevent version 0.13.7 libevent has been replaced with libev due to simplicity of this library compared with libevent and other things).

With the patch you can check that gevent is working properly in tests.

I will do the pull request to develop branch but I have checked that it has a trivial conflict like:

```
+++ b/sleekxmpp/test/sleektest.py
@@@ -7,11 -7,17 +7,25 @@@
  """

  import unittest
++<<<<<<< HEAD
 +from xml.parsers.expat import ExpatError
 +try:
 +    import Queue as queue
 +except:
 +    import queue
++=======
+ import sys
+ #Correct import of queue if gevent module is loaded
+ if sys.modules.has_key('gevent'):
+     import gevent.queue as queue
+     Queue = queue.JoinableQueue
+ else:
+     try:
+         import queue
+     except ImportError:
+         import Queue as queue
+     Queue = queue.Queue
++>>>>>>> spartan_sleekxmpp/develop_spartanbits
```

Could you resolve it when you accept the pull request?

Thanks for your reply!!!

**Comment by pvicente** [comment]
Also I have checked that develop branch has 78 error tests

**Comment by pvicente** [comment]
Sorry tests are ok, I had not installed gpg command ...

**Comment by chason** [comment]
Has this patch been accepted yet? I would love to use gevent with my SleekXMPP apps.

**Comment by legastero** [comment]
@chason I'm still reviewing. The test suite works great and zooms when using the gevent queues and monkeypatcher, but so far running an actual client just hangs.

But, I've just finished some reorganization, so now all queue class references are imported from sleekxmpp.util, so if you want to experiment, it's a very simple edit in one spot.

**Comment by gabriel-samfira** [comment]
@legastero  I had to edit line 37 of xmlstream/filesocket.py and change:

<pre>
  class Socket26(socket._socketobject):
</pre>

to:

<pre>
  class Socket26(socket.socket):
</pre>

as well as sleekxmpp.util. I'm trying it right now. Under what conditions have you noticed it hang? Have you had a chance to try it against gevent 1.0b4?

**Comment by legastero** [comment]
@gabriel-samfira That socketobject change may be what I missed when I tested. But when running an actual client it would just hang after receiving the first stream header and features. I've not had a chance to come back and test since then.

If you have a diff against the latest master or develop which works both in tests and running echo client, please send it my way or make a pull request.

**Comment by gabriel-samfira** [comment]
I've tested the latest checkout of sleekxmpp with gevent 1.0b4 and it seems to work great. I used 1.0b4 because the latest stable version gives a timeout in DNS resolution if you daemonize it (at least on my system).

Tests run fine, and the echo_client.py runs great. This diff is basically an update to what pvicente already did.

<pre>
diff --git a/sleekxmpp/util/__init__.py b/sleekxmpp/util/__init__.py
index 7637dda..70740f4 100644
--- a/sleekxmpp/util/__init__.py
+++ b/sleekxmpp/util/__init__.py
@@ -17,11 +17,15 @@ from sleekxmpp.util.misc_ops import bytes, unicode, hashes, hash, \
 # =====================================================================
 # Standardize import of Queue class:
 
-try:
-    import queue
-except ImportError:
-    import Queue as queue
+import sys
+if sys.modules.has_key('gevent'):
+    import gevent.queue as queue
+    Queue = queue.JoinableQueue
+else:
+    try:
+        import queue
+    except ImportError:
+        import Queue as queue
+    Queue = queue.Queue
 
-
-Queue = queue.Queue
 QueueEmpty = queue.Empty
diff --git a/sleekxmpp/xmlstream/filesocket.py b/sleekxmpp/xmlstream/filesocket.py
index 56554c7..d453799 100644
--- a/sleekxmpp/xmlstream/filesocket.py
+++ b/sleekxmpp/xmlstream/filesocket.py
@@ -34,7 +34,7 @@ class FileSocket(_fileobject):
             return data
 
 
-class Socket26(socket._socketobject):
+class Socket26(socket.socket):
 
     """A custom socket implementation that uses our own FileSocket class
     to work around issues in Python 2.6 when using sockets as files.
</pre>

**Comment by legastero** [comment]
Whatever issue I was experiencing, after reinstalling gevent with 1.0b4 everything works great. I think I actually had 0.13 installed before. So this is now merged, with much rejoicing.

The only downside/gotcha that I've found so far is that ctrl-c handling is not the same with gevent loaded.

**Comment by gabriel-samfira** [comment]
Also, gevent does not have _socketobject. Be sure to watch out for that one if you need to inherit the socket in any other classes. But as far as I can tell, socket._socketobject and socket.socket are the same thing, so it should be fine :).

Thanks for the merge :D.

**Comment by pvicente** [comment]
Hi, the main reason of using socket.socket on gevent is to work fine with monkey patching. The objects are the same but monkey patching only patch socket.socket object.

Thanks for the merge.

**Pull request closed without merging**
