### PR TITLE
XEP-0332: HTTP over XMPP transport

### PR DESCRIPTION
**Pull request by sangeeths**
Reference: http://xmpp.org/extensions/xep-0332.html

Please go through examples/http_over_xmpp.py for reference.

### CODE REVIEW

**Comment by bear** [comment]
@sangeeths I ran the test suite under Python 2.7 and it found multiple failures. Can you take a look at this with the latest develop branch?

thanks

**Comment by bear** [comment]
looks like I misread the output and it's not XEP 0332 that is failing but rather 0323 - rerunning tests now

**Comment by bear** [comment]
woo - all tests pass - merging!

**Comment by sangeeths** [comment]
@bear Thanks for the merge! :)

**Pull request merged**
