### PR TITLE
Fixes compatibility issues with pyasn1 >= 0.4.1

### PR DESCRIPTION
**Pull request by kdschlosser**
This is a multi part Problem.

Part 1. Is the year of the certificates. You have provided a solution for this. I have altered this solution because of the second part.

Part 2. There is a traceback the occurs when the TLS certificate is checked. 

    pyasn1.error.PyAsn1Error: <TagSet object at 0x7f53f5fb74e0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f53f5f51d68 tagSet <TagSet object at 0x7f540c3cef28 tags 0:0:4> encoding iso-8859-1>

This traceback has been reported to the maker(s) of pyasn1.

https://github.com/etingof/pyasn1/issues/112

#477 also describes the problem.

This issue was closed with a half explained solution. I have instituted this solution into the sleekXMPP library.

I added version checking of the pyasn1 module, because of this the checking of the date instances is not needed (or at least I do not think it is). If the pyasn1 version is >= 0.4.1 then a flag is set to use the alternate means of grabbing the needed certificate information.

### CODE REVIEW

**Comment by kdschlosser** [comment]
i was reading through some of the issues and PR's and I noticed a fix for the year issue that seems to be a correct solution. As I now know mine is wrong as well.

If you merge PR #472, I will make a new commit using the merged code if needed.

**Comment by ammgws** [comment]
Just got bitten by this one again after using SleekXMPP in a new project - thought this fix would have been merged by now. Downgraded pyasn1 for now...

**Comment by Semperverus** [comment]
@ammgws which version of it did you have to downgrade to in order to make it work? I just started playing with this and am having the same issue.

**Comment by ammgws** [comment]
pyasn1          0.3.7    
pyasn1-modules  0.1.5
sleekxmpp       1.3.1

**Comment by bear** [comment]
thanks for looking into and fixing this!

**Comment by kdschlosser** [comment]
oh wow i fixed this a while ago. I completely forgot about it.

**Comment by oonid** [comment]
so, any plan for releasing a new version with pyasn1 >= 0.4.1 compatible?
especially new version on pypi.
(and also close this issue).
thank you.

**Comment by ammgws** [comment]
This is still broken when installing via pip.
Is there anything preventing the version from being bumped to 1.3.4?
It's been over a year...

**Comment by ammgws** [comment]
@legastero If you have some spare time could you please look into cutting a new release and/or updating the version on pypi?

**Comment by lpsinger** [comment]
@fritzy, are you still maintaining this package? If not, would you be willing to hand off maintaining it to another user?

**Comment by aylen384** [comment]
Most people are using the slixmpp fork now, which is even packaged Debian.

**Pull request merged**
