### PR TITLE
elide copies

### PR DESCRIPTION
**Pull request by vijayp**
There a lot of places where stanzas are copied. this is a pretty expensive operation (deepcopy is often used), and should be avoided whenever possible.

Ideally, event handlers should not be permitted to modify data passed in, but that will require a change in RPC. An additional way to do this would be to write a COW data wrapper, but that is a lot of work, and too ugly.

I solved the issue by not doing any copying when there is only one matching handler when the data is not used after the handler executes, and also eliminating unnecessary/duplicated copies.

This passes all unittests.

### CODE REVIEW

**Comment by legastero** [comment]
I'm merging this in to develop right now and adding more unit tests to make sure things work as expected.

**Comment by legastero** [comment]
This is in develop now, with the filter issue replaced with a comprehension.

Thanks for the optimization work! Any tools in particular that you are using to do the measurements?

**Comment by vijayp** [comment]
On Sat, Nov 19, 2011 at 18:52, Lance Stout
reply@reply.github.com
wrote:

> This is in develop now, with the filter issue replaced with a comprehension.
> 
> Thanks for the optimization work! Any tools in particular that you are using to do the measurements?

Yeah, I have hacked up the code to work with cProfile  -- I'm running
it with tornado, so I periodically access the objects and dump out the
file, then use the gprof2dot tool online to convert it into a dot
file. It's particularly ugly because cProfile does not work well with
threads and your sleek implementation is thread-based. I could
probably do the dumping out using another worker thread actually. I'll
try to clean it up and send it in sometime soon, but I'm pretty busy
and this is all for an open source project.

**Comment by vijayp** [comment]
There is actually another opt fix I have done.  Just have to clean it up

**Pull request merged**
