### PR TITLE
Don't use dnspython for A and AAAA (but keep it for SRV).

### PR DESCRIPTION
**Pull request by guilhem**
dnspython don't perform a full resolv.
For example it don't manage /etc/hosts on linux.

### CODE REVIEW

**Comment by guilhem** [comment]
This fix sleekxmpp fail when realm is set in /etc/hosts and dnspython is installed.

**Comment by joepie91** [comment]
Have not reviewed the patch, but +1 on the intention.

/etc/hosts being ignored when dnspython is a very annoying (and unpredictable) issue during development.

**Comment by guilhem** [comment]
:up: 

It's quite important for us and break all our application.
(and pip is now quite a pain in ass with external dependencies)

Thank you

**Comment by guilhem** [comment]
Thanks @legastero

**Comment by mofrank** [comment]
This change has caused major issues for us.  With dnspython doing srv and the os responsible for A records we are getting unpredictable results.   It is especially a  problem at the moment of a network change where we have full control of dnspython and can re-read the /etc/resolv.conf but for the A record we are at the mercy of negative cache results etc.

I assume the comments above about dnspython ignoring /etc/resolv.conf are actually that dnspython does not detect changes  to resolv.conf.    This impacts SRV records as well as A records.  In our implementation we addressed this by using the intended user exit ( overriding the configure_dns method ) and re-reading the /etc/resolv.conf  

Is there a way to get dnspython back, at least as an option for resolution of A records

**Comment by legastero** [comment]
Changed in v1.3.0 so that the flag `use_dnspython` must be set to `True` to enable using dnspython for A/AAAA resolution.

So the original use case for this PR now only requires `sleekclient.use_dnspython = False`

**Comment by guilhem** [comment]
@legastero what is the default behaviour?

**Comment by joepie91** [comment]
The change appears to be introduced in ad91a8. Per the diff at https://github.com/fritzy/SleekXMPP/commit/ad91a8cd5ebff56ee0cb84edbc7f0574e9c19911#diff-9d3e8ac3363491e3a588f4685a0a4e00R56, it would seem that the default is `True`, thus using `dnspython` by default.

EDIT: Wow. I don't think the GitHub URL converter was built to deal with line-specific URLs for commits...

**Comment by guilhem** [comment]
@legastero Adding an option to use dnspython can be good (even if I really think it's a bad things and problem come from architecture, not software).

But why putting this by default?
That's really a non-sense because dnspython doesn't do a "good" `A` or `AAAA` resolve.
If someone is aware of this behavior, he may activate this.
But it can lead to many problems for common user... many real problems.

**Comment by mofrank** [comment]
The problem I run into is a missmatch in the version of resolve.conf.
where for dnspython we may have forced a reread of the config but the non
dnspytho. Approach may not have reread the config.  Or worse may have
different negative cache

**Pull request merged**
